---
- name: Create pods using deployment 
  hosts: kubernetes-master
  user: devsecops
 
  tasks: 
  - name: create a deployment
    shell: chdir=/home/devsecops kubectl apply -f k8s-demo-deploy.yml
 
  - name: update deployment with new pods if image updated in nexus
    shell: kubectl rollout restart deployment.v1.apps/demo-deployment
