apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-project
spec:
  selector:
    app: demo-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
